### ISSUE TITLE
erroe

### ISSUE THREAD

**Issue by LiJing157** [jean997/IBDsims#1]
hello,Jean Morrison,
       when I run the command in IBD_sim_doc.pdf:python .\recomb_sim.py --fam=example.fam --chr-lengths=example.chr_lengths.txt --out=example.chr_diag.txt;all example files from Simulate_IBD_Python dirs; but the program will report an error;can you help me ?or tell me the reason?thanks

Traceback (most recent call last):
  File ".\recomb_sim.py", line 125, in <module>
    G=gethap(cur_cd, fam, i, fgl, clength, rate)
  File ".\recomb_sim.py", line 72, in gethap
    elif len(cur_cd[P][parent])==0:
KeyError: b'0'

**Comment by jean997** [comment]
Hi,
I'm sorry - this is code that I wrote over 10 years ago so I am not surprised that it is giving errors. It originally ran in python 2 and I never tested it in python 3. This isn't software that I actively maintain. 

If you really need this to run, I would suggest to start by running it in python 2. You might also find newer software that does the same thing. 
(This one maybe? https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2611-1)

If you can't find alternatives and can't get it to run in python 2, I may be able to find the time to look into it in the next few weeks but unfortunately I cant do this immediately.
Jean

**Comment by LiJing157** [comment]
Hi，


&nbsp; &nbsp; Thank you very much for your reply. I will try to run it in python2 or other newer software.&nbsp;Whether I can run successfully in python2 or not, I will get back to you.&nbsp;&nbsp;Thank you very much.


Jing




平平淡淡
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jean997/IBDsims"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 上午6:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jean997/IBDsims] erroe (Issue #1)





 
Hi,
 I'm sorry - this is code that I wrote over 10 years ago so I am not surprised that it is giving errors. It originally ran in python 2 and I never tested it in python 3. This isn't software that I actively maintain.
 
If you really need this to run, I would suggest to start by running it in python 2. You might also find newer software that does the same thing.
 (This one maybe? https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2611-1)
 
If you can't find alternatives and can't get it to run in python 2, I may be able to find the time to look into it in the next few weeks but unfortunately I cant do this immediately.
 Jean
